### ISSUE TITLE
Enhancement: Get posts of last 1-2 week(s) instead of last day

### ISSUE THREAD

**Issue by karaeren** [butttons/reddit-trends#1]
Getting the posts from last day can give misleading information about a subreddit. For example, a subreddit can have a score of 250 (based on your algorithm) at 2 PM on Mondays but a score of 100 at 2 PM on Fridays. Getting the posts from last 1 or more weeks would give a better idea...

**Comment by butttons** [comment]
It's not actually getting just the last day, it is getting all the posts till the limit has been reached, or there are no more posts to fetch.

I've added a label for showing the time of the oldest post in the dataset. 
Will probably add a timeline chart for that info, just aggregating the total number of posts of a day.

**Comment by karaeren** [comment]
Oh ok, since it only shows times for 1 day, I thought it was getting last days posts. Some sort of 2 sided graph like a heatmap would be cool to see.
